### ISSUE TITLE
Some question about this 16k model

### ISSUE THREAD

**Issue by yemifeng** [YongyuG/rnnoise_16k#3]
Thanks for sharing this 16 k model. However, there are still exist some questions that make me confusing.

(1) As far as I know, pitch feather is important. The original code about pitch analysis is conducted in 48 kHz. In your example, only the macros PITCH_MIN_PERIOD, PITCH_MAX_PERIOD and PITCH_FRAME_SIZE are revised. So, have you ever tested wheter the code could extract pitch correctly with only small revise?

(2) Have you ever test this model with the performance of PESQ?  Using the original RNNOISE code, the PESQ is good, however, using the weight with my own training, it is not very good.  

Thanks very much.

**Comment by YongyuG** [comment]
> Thanks for sharing this 16 k model. However, there are still exist some questions that make me confusing.
> 
> (1) As far as I know, pitch feather is important. The original code about pitch analysis is conducted in 48 kHz. In your example, only the macros PITCH_MIN_PERIOD, PITCH_MAX_PERIOD and PITCH_FRAME_SIZE are revised. So, have you ever tested wheter the code could extract pitch correctly with only small revise?
> 
> (2) Have you ever test this model with the performance of PESQ? Using the original RNNOISE code, the PESQ is good, however, using the weight with my own training, it is not very good.
> 
> Thanks very much.

1. very good question,pitch filter is a  comb filter to reduce the pitch harmonic effect due to low resolution of using bfcc.
Therefore, the macro which in my opinion, is param to define that comb filter. I believe there must be somewhere else required to modify the code where changing the samplerate, but for my perspective, 16k or 8k are under 48kHz, changing macro params are ok for me.

2. I have tested with pesq, which show improvement in babble noise and some werid noise comparing with 48K. I think you test should be established on various snr, noise types and models
